#!/usr/bin/ansible-playbook

- name: setup owncloud in docker
  hosts: owncloud
  vars:
    # modify these
    OWNCLOUD_ADMIN_USERNAME: admin
    OWNCLOUD_ADMIN_PASSWORD: admin
    OWNCLOUD_DOMAIN: localhost
    OWNCLOUD_HTTP_PORT: 8080
    OWNCLOUD_VERSION: latest
    OWNCLOUD_ROOT: "{{ ansible_env.HOME }}/owncloud"
    docker_install: yes
  tasks:

    - name: setup docker
      when: docker_install
      include_role:
        name: geerlingguy.docker
      vars:
        ansible_become: yes
        docker_users: ["{{ ansible_user }}"]

    - name: mkdir owncloud
      file:
        path: "{{ OWNCLOUD_ROOT }}"
        state: directory

    - name: render docker-compose.yml
      template:
        src: docker-compose.yml
        dest: "{{ OWNCLOUD_ROOT }}/docker-compose.yml"
        force: yes

    - name: apt install supervisor
      become: yes
      apt:
        update_cache: yes
        name: supervisor

    - name: render owncloud supervisor conf
      become: yes
      template:
        src: owncloud.conf
        dest: /etc/supervisor/conf.d/owncloud.conf
        force: yes

    - name: supervisorctl restart
      become: yes
      supervisorctl:
        name: owncloud
        state: restarted
